apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: {{ .Values.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ .Values.namespace }}
    name: {{ .Values.spec.destination.name }}
  project: default
  source:
    path: app
    repoURL: https://github.com/joenatan/app-airflow
    targetRevision: HEAD
